name: Build Injected IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          brew install insert_dylib

      - name: Unzip IPA
        run: |
          mv *.tipa app.zip
          unzip app.zip

      - name: Inject dylib
        run: |
          APP=$(ls Payload/*.app)
          APP_NAME=$(basename "$APP" .app)

          echo "App path: $APP"
          echo "Binary: $APP_NAME"

          mkdir -p "$APP/Frameworks"

          cp *.dylib "$APP/Frameworks/"
          cp *.plist "$APP/"

          insert_dylib @executable_path/Frameworks/XXTouchHack.dylib "$APP/$APP_NAME" --inplace

      - name: Repack IPA
        run: |
          zip -r injected.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: injected-ipa
          path: injected.ipa
