name: Build Injected IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          brew install llvm
          git clone https://github.com/tyilo/insert_dylib.git
          cd insert_dylib
          clang insert_dylib/main.c -o insert_dylib
          chmod +x insert_dylib
          mv insert_dylib /usr/local/bin/

      - name: Unzip IPA
        run: |
          mv *.tipa app.zip
          unzip app.zip

      - name: Inject dylib
        run: |
          APP=$(ls Payload/*.app)
          APP_NAME=$(basename "$APP" .app)

          mkdir -p "$APP/Frameworks"

          cp *.dylib "$APP/Frameworks/"
          cp *.plist "$APP/"

          insert_dylib @executable_path/Frameworks/XXTouchHack.dylib "$APP/$APP_NAME" --inplace

      - name: Repack IPA
        run: |
          zip -r injected.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: injected-ipa
          path: injected.ipa
